---
- name: Install lemp stack
  hosts: all
  become: true
  
  tasks:
   - name: Add repository
     yum_repository:
       name: mysql-server
       description: mysql repo
       baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/6/$basearch/

   - name: Install LEMP Packages
     yum: name={{ item }} update_cache=yes state=latest
     loop: [ 'nginx', 'mysql-server', 'php-fpm', 'php-mysql' ]

# Nginx Configuration

   - name: copy the nginx config file
     ansible.builtin.copy:
        src: /files/default.cfg
        dest: /etc/nginx/sites-available/default.cfg
        become: true

   - name: Create a symbolic link
     ansible.builtin.file:
        src: /etc/nginx/sites-available/default.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link

# MySQL Configuration

   - name: Sets the root password
     mysql_user:
       name: root
       password: "{{ password }}"
       login_unix_socket: /var/run/mysqld/mysqld.sock

 # UFW Configuration

   - name: "UFW - Allow HTTP on port {{ 80 }}"
     ufw:
       rule: allow
       port: "{{ 80 }}"
       proto: tcp

# Sets Up PHP Info Page

   - name: Sets Up PHP Info Page
     template:
       src: "files/info.php.j2"
       dest: "/var/www/html/info.php"

# Handlers

   - name: Reload Nginx
     service:
       name: nginx
       state: reloaded

   - name: Restart Nginx
     service:
       name: nginx
       state: restarted
